name: Greeting_Logic
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  Greeting:
    runs-on: ubuntu-latest
    
    steps:
      - name: Greeting with name
        run: echo Welcome ${{inputs.name}} to github actions
