name: Testing File

on:
  workflow_dispatch

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a 1 line script
        run: echo Hello, World!
       
      - name: Run a multi line script
        run: |
          echo Multi Line 1
          echo Multi Line 2
          
