name: Twist Lock Scan

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Name of the image to be scanned'
        required: true
        type: string
        
jobs:
  run-twistlock-scan:
    runs-on: ubuntu-latest

    steps:
      - name: PISO Twistlock Scan
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1
        with:
          pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
          pcc_user: ${{ secrets.PCC_USER }}
          pcc_pass: ${{ secrets.PCC_PASS }}
          image_name: ${{ inputs.image_name }}
