name: Twist Lock Scan

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Name of the image to be scanned, Make sure the same is used for exporting the file'
        required: false
        type: string
        
jobs:
  twistlock-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading image
        uses: actions/download-artifact@v3
        with: 
          name: bkob
          
      - name: checking files
        run: ls -la
      
      - name: Importing the Docker Image
        run: |
          docker load -i bkob.tar
          docker images | grep bkob
      
      - name: PISO Twistlock Scan
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1
        with:
          pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
          pcc_user: ${{ secrets.PCC_USER }}
          pcc_pass: ${{ secrets.PCC_PASS }}
          image_name: bkob          
          
