name: "Twistlock scan using own cli"
description: "performing twistlock scan using own cli"

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Name of the image to be scanned'
        required: true
        type: string
        
jobs:
  scan-using=twist-cli:
    runs-on: ubuntu-latest
    
    steps:
      - name: Downloading twistcli
        run: |
          curl -s -k -L -u ${{secrets.PCC_USER}}:${{secrets.PCC_PASS}} https://gps-twistlock.ift.pearsondev.tech/api/v1/util/twistcli > twistcli && chmod 0755 twistcli
          ./twistcli images scan -u ${{secrets.PCC_USER}} -p ${{secrets.PCC_PASS}} --address ${{secrets.PCC_CONSOLE_URL}} --details --output-file twistcli.log --tarball ${{inputs.image_name}} 
          
